#!/usr/bin/env node
// Measures how loud each voice clip is, 30 times a second, so the characters' mouths can
// move with their lines. Writes voices-lips.js: window.LIPS["Speaker|caption"] = "0357...".
// Needs Playwright (npm i -g playwright) — the browser decodes the MP3s.
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
let pw; try { pw = require('playwright'); } catch { pw = require(require('child_process').execSync('npm root -g').toString().trim() + '/playwright'); }
(async () => {
  const src = fs.readFileSync(path.join(ROOT, 'voices.js'), 'utf8');
  const map = JSON.parse(src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1));
  const b = await pw.chromium.launch();
  const p = await b.newPage();
  const out = {};
  for (const [key, file] of Object.entries(map)) {
    const b64 = fs.readFileSync(path.join(ROOT, file)).toString('base64');
    out[key] = await p.evaluate(async b64 => {
      const bytes = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
      const ctx = new OfflineAudioContext(1, 1, 24000);
      const buf = await ctx.decodeAudioData(bytes.buffer);
      const d = buf.getChannelData(0), win = Math.round(buf.sampleRate / 30), lv = [];
      for (let i = 0; i < d.length; i += win) {
        let s = 0; for (let j = i; j < Math.min(i + win, d.length); j++) s += d[j] * d[j];
        lv.push(Math.sqrt(s / win));
      }
      const peak = Math.max(...lv) || 1;
      return lv.map(v => Math.min(9, Math.round(Math.pow(v / peak, .7) * 9))).join('');
    }, b64);
  }
  await b.close();
  fs.writeFileSync(path.join(ROOT, 'voices-lips.js'),
    '// Generated by tools/make_lips.js — mouth-open levels (0-9) at 30 per second for each clip.\nwindow.LIPS = ' + JSON.stringify(out, null, 1) + ';\n');
  console.log(Object.keys(out).length, 'clips measured');
})();
