#!/usr/bin/env python3
"""Generate the character voice clips with OpenAI text-to-speech.

Reads voices/lines.json (["Speaker", "caption text"] pairs), writes one MP3 per
line into voices/, and writes voices.js mapping "Speaker|caption text" to its clip.
Only lines without a clip are generated, so re-running after a wording change is cheap.

Needs an OpenAI API key in OPENAI_API_KEY (or a proxy that adds it).
"""
import hashlib, json, os, re, sys, urllib.request
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = "gpt-4o-mini-tts"
AKELA_SAYS = " The word Akela is pronounced ah-KAY-lah."
CAST = {
    "Narrator": ("fable", "Warm, cozy storyteller reading a picture book aloud to young children. Gentle wonder, unhurried, smiling."),
    "Akela":    ("onyx",  "A kind, wise, grandfatherly Cub Scout leader speaking at a campfire ceremony. Warm, proud, calm and a little theatrical, with meaningful pauses."),
    "Max":      ("nova",  "An excited seven-year-old boy who can barely contain his joy. Bouncy, high energy, breathless, giggly, childlike."),
    "Mom":      ("coral", "A loving, cheerful mom, warm and a little teary with pride, playful and giggly."),
    "Dad":      ("ash",   "A friendly, goofy, proud dad. Warm and relaxed with a playful grin."),
    "Bobcat":   ("verse", "A playful, mischievous cartoon bobcat mascot. Sly, sparkly, conspiratorial, bursting with excitement."),
}
RECITING = "An earnest seven-year-old boy proudly reciting from memory at his Cub Scout ceremony: clear, careful, heartfelt, a little excited."

def spoken(text):
    """What the voice actually reads (captions keep the original text)."""
    text = re.sub(r"[\U0001F000-\U0001FFFF☀-➿️]", "", text)
    return text.replace("149", "one forty-nine")

def clip_name(speaker, text):
    return f"{speaker.lower()}-{hashlib.sha1((speaker + '|' + text).encode()).hexdigest()[:10]}.mp3"

def main():
    lines = json.load(open(os.path.join(ROOT, "voices", "lines.json")))
    html = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
    oath_law = html[html.index("const OATH"):html.index("const MOTTO")]
    recited = set(re.findall(r"'([^']+)'\]", oath_law))
    key = os.environ.get("OPENAI_API_KEY")

    def make(pair):
        speaker, text = pair
        out = os.path.join(ROOT, "voices", clip_name(speaker, text))
        if os.path.exists(out):
            return "kept"
        voice, style = CAST[speaker]
        if speaker == "Max" and (text in recited or text.rstrip(",!") in recited or text == "A Scout is..."):
            style = RECITING
        if "Akela" in text:
            style += AKELA_SAYS
        body = json.dumps({"model": MODEL, "voice": voice, "input": spoken(text),
                           "instructions": style, "response_format": "mp3"}).encode()
        req = urllib.request.Request("https://api.openai.com/v1/audio/speech", data=body,
                                     headers={"Content-Type": "application/json"})
        if key:
            req.add_header("Authorization", "Bearer " + key)
        with urllib.request.urlopen(req, timeout=120) as r, open(out, "wb") as f:
            f.write(r.read())
        return "made"

    with ThreadPoolExecutor(6) as pool:
        results = list(pool.map(make, lines))
    print(f"{results.count('made')} made, {results.count('kept')} already existed")

    mapping = {f"{s}|{t}": "voices/" + clip_name(s, t) for s, t in lines}
    with open(os.path.join(ROOT, "voices.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/make_voices.py — maps \"Speaker|caption\" to a voice clip.\n")
        f.write("window.VOICES = " + json.dumps(mapping, indent=1, ensure_ascii=False) + ";\n")

if __name__ == "__main__":
    sys.exit(main())
