#!/usr/bin/env python3
"""Find when each word is spoken in selected voice clips (OpenAI Whisper word timestamps).

Writes voices-timing.js: window.WORD_TIMES["Speaker|caption"] = [[word, start_seconds], ...].
The Scout Law scene uses it to pop each badge up as Max says that word.
Needs OPENAI_API_KEY (or a proxy that adds it). Re-run after re-recording a timed line.
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TIMED = lambda speaker, text: text.startswith("A Scout is ")   # which lines need word timings

def transcribe(path):
    cmd = ["curl", "-sS", "--max-time", "120", "https://api.openai.com/v1/audio/transcriptions",
           "-F", f"file=@{path}", "-F", "model=whisper-1", "-F", "response_format=verbose_json",
           "-F", "timestamp_granularities[]=word", "-F", "language=en"]
    if os.environ.get("OPENAI_API_KEY"):
        cmd += ["-H", "Authorization: Bearer " + os.environ["OPENAI_API_KEY"]]
    out = json.loads(subprocess.run(cmd, capture_output=True, text=True, check=True).stdout)
    if "words" not in out:
        sys.exit("transcription failed: " + json.dumps(out)[:300])
    return [[w["word"], round(w["start"], 3)] for w in out["words"]]

src = open(os.path.join(ROOT, "voices.js"), encoding="utf-8").read()
clips = json.loads(src[src.index("{"):src.rindex("}") + 1])
times = {}
for key, file in clips.items():
    speaker, text = key.split("|", 1)
    if TIMED(speaker, text):
        times[key] = transcribe(os.path.join(ROOT, file))
        print(key[:60], "->", " ".join(f"{w}@{t}" for w, t in times[key]))
with open(os.path.join(ROOT, "voices-timing.js"), "w", encoding="utf-8") as f:
    f.write("// Generated by tools/word_times.py: when each word starts (seconds) in timed voice clips.\n")
    f.write("window.WORD_TIMES = " + json.dumps(times, ensure_ascii=False) + ";\n")
